# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_1000GeV --cardOut datacard_Graviton_1000GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_1200GeV --cardOut datacard_Graviton_1200GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_260GeV  --cardOut datacard_Graviton_260GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_270GeV  --cardOut datacard_Graviton_270GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_300GeV  --cardOut datacard_Graviton_300GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_350GeV  --cardOut datacard_Graviton_350GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_400GeV  --cardOut datacard_Graviton_400GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_450GeV  --cardOut datacard_Graviton_450GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_500GeV  --cardOut datacard_Graviton_500GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_550GeV  --cardOut datacard_Graviton_550GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_600GeV  --cardOut datacard_Graviton_600GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_650GeV  --cardOut datacard_Graviton_650GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_750GeV  --cardOut datacard_Graviton_750GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_800GeV  --cardOut datacard_Graviton_800GeV.txt
# python make_datacard.py --sel selectionbJetsHH_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb/outPlotter.root --bkgs data_BTagCSV_Background --sigs sig_Graviton_900GeV  --cardOut datacard_Graviton_900GeV.txt

# python make_datacard_NMMSM_XYH_bbbb.py --var HH_m_H2_m_Rebinned_Unrolled --sel selectionbJetsAndTrigger_4bTag_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_PtRegressedAndHigherLevel_VCR_30_VSR_10/outPlotter.root --bkgs data_BTagCSV_dataDriven --bkgsSel selectionbJetsAndTrigger_3bTag --sigs sig_privateMC_NMSSM_bbbb_MX_700_MY_300  --cardOut datacard_privateMC_NMSSM_bbbb_MX_700_MY_300.txt
# python make_datacard_NMMSM_XYH_bbbb.py --var HH_m_H2_m_Rebinned_Unrolled --sel selectionbJetsAndTrigger_4bTag_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_PtRegressedAndHigherLevel_VCR_30_VSR_10/outPlotter.root --bkgs data_BTagCSV_dataDriven --bkgsSel selectionbJetsAndTrigger_3bTag --sigs sig_privateMC_NMSSM_bbbb_MX_900_MY_200  --cardOut datacard_privateMC_NMSSM_bbbb_MX_900_MY_200.txt


python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_300_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_300_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_400_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_400_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_500_MY_300 --cardOut datacard_sig_NMSSM_bbbb_MX_500_MY_300.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_300 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_300.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_600_MY_400 --cardOut datacard_sig_NMSSM_bbbb_MX_600_MY_400.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_300 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_300.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_400 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_400.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_700_MY_500 --cardOut datacard_sig_NMSSM_bbbb_MX_700_MY_500.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_300 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_300.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_400 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_400.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_500 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_500.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_800_MY_600 --cardOut datacard_sig_NMSSM_bbbb_MX_800_MY_600.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_60  --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_60.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_70  --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_70.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_80  --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_80.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_90  --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_90.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_100 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_100.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_125 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_125.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_150 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_150.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_200 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_200.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_250 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_250.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_300 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_300.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_400 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_400.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_500 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_500.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_600 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_600.txt
python make_datacard.py --sel selectionbJets_SignalRegion --fileIn ../2016DataPlots_NMSSM_XYH_bbbb_Fast/outPlotter.root --bkgs data_BTagCSV_dataDriven --sigs sig_NMSSM_bbbb_MX_900_MY_700 --cardOut datacard_sig_NMSSM_bbbb_MX_900_MY_700.txt


