#NMSSM_XYH_bbbb_2016
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_MY_700_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_1200_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_700_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1200_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1800_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_MY_60_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_MY_300_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_MY_100_privateMC.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_MY_200_privateMC.txt


#NMSSM_XYH_bbbb_2016 backgrounds
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/GluGluHToBB_M125_13TeV_powheg_pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/ZZTo4Q_13TeV_amcatnloFXFX_madspin_pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016NonResonantDiHiggs4BDataSets/ttHTobb_M125_13TeV_powheg_pythia8.txt


# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYHbbbb_privateProduction_forTrigger.txt

# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/TTTo2L2Nu_TuneCP5_13TeV.txt --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/TTTo2L2Nu_TuneCP5_13TeV.txt --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights


#NMSSM_XYH_bbbb_2016 fast 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7.txt 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7.txt  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7.txt  

#NMSSM_XYH_bbbb_2016 full 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7_Full.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7_Full.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights 


# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 


# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 

# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 


# NMSSM_2016_background
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/ttHTobb_M125_13TeV_powheg_pythia8.txt                       --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/ZZTo4bQ01j_5f_TuneCP5_amcatNLO_FXFX_pythia8.txt             --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8.txt                --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt            --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt           --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix.txt           --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/GluGluHToBB_M125_13TeV_powheg_pythia8.txt                   --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016_NMSSM_XYH_bbbb_Datasets/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt                  --outputFolder=weights/2016_NMSSM_XYH_bbbb_weights


#NMSSM_XYH_bbbb_2017 full 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7_Full.txt   --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 
get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7_Full.txt  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights 

# # NMSSM_2017_background
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt                  --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8.txt          --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8.txt          --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8.txt         --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8.txt         --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/GluGluHToBB_M125_TuneCP5_13TeV-powheg-pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/ZZTo4bQ01j_5f_TuneCP5_amcatNLO_FXFX_pythia8.txt             --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8.txt                --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt            --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/ttHTobb_M125_TuneCP5_13TeV-powheg-pythia8.txt               --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt               --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/2017_NMSSM_XYH_bbbb_Datasets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt           --outputFolder=weights/2017_NMSSM_XYH_bbbb_weights


#NMSSM_XYH_bbbb_2018 full 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_500_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_600_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_800_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_NANOAOD_v7_Full.txt   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1100_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1200_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1400_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1800_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_NANOAOD_v7_Full.txt  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights 

## NMSSM_2018_background
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt                  --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8.txt       --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8.txt        --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8.txt        --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8.txt        --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8.txt       --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8.txt      --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8.txt      --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/GluGluHToBB_M125_13TeV_powheg_pythia8.txt                   --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/ttHTobb_M125_TuneCP5_13TeV-powheg-pythia8.txt               --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/ZZTo4bQ01j_5f_TuneCP5_amcatNLO_FXFX_pythia8.txt             --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8.txt                --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt            --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8.txt           --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix.txt           --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt           --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/2018_NMSSM_XYH_bbbb_Datasets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt               --outputFolder=weights/2018_NMSSM_XYH_bbbb_weights


# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root --input inputFiles/TriggerEfficiencyMeasurement/gg_HH_4B_SM_2017_forTrigger.txt  
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root --input inputFiles/TriggerEfficiencyMeasurement/gg_HH_4B_SM_2018_forTrigger.txt  


#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt
#get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root --input inputFiles/2016ResonantDiHiggs4BDataSets/MC_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt


# #2016 NON RESONANT SAMPLES
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph.txt                  
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/GluGluToHHTo4B_node_SM_13TeV-madgraph_2_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph_2.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.txt --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt         
# get_sample_PU_weights.exe --realPU weights/Collision16PileupHistogram.root --realPU_up weights/Collision16PileupHistogramUp.root --realPU_down weights/Collision16PileupHistogramDown.root -output weights/2016/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph_PUweights.txt  --input inputFiles/2016NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph.txt              
# ##2017 NONRESONANT SAMPLES
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg_PUweights.root --input inputFiles/2017NonResonantDiHiggs4BDataSets/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root    --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root    --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_PUweights.root             --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_PUweights.root          --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.root           --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.root     --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph_PUweights.root           --input inputFiles/2017NonResonantDiHiggs4BDataSets/VBFHHTo4B_CV_1_C2V_2_C3_1_13TeV-madgraph.txt
# get_sample_PU_weights.exe --realPU weights/Collision17PileupHistogram.root --realPU_up weights/Collision17PileupHistogramUp.root --realPU_down weights/Collision17PileupHistogramDown.root  --output weights/2017/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8_PUweights.root      --input inputFiles/2017NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8.txt
# ##2018 NONRESONANT SAMPLES
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8.root --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8.root --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root  --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8.root   --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8.root  --input inputFiles/2018NonResonantDiHiggs4BDataSets/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root             --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.root          --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.root      --input inputFiles/2018NonResonantDiHiggs4BDataSets/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt
# get_sample_PU_weights.exe --realPU weights/Collision18PileupHistogram.root --realPU_up weights/Collision18PileupHistogramUp.root --realPU_down weights/Collision18PileupHistogramDown.root  --output weights/2018/ZZTo4bQ01j_5f_amcatNLO_FXFX_pythia8.rooot               --input inputFiles/2018NonResonantDiHiggs4BDataSets/ZZTo4bQ01j_5f_amcatNLO_FXFX_pythia8.txt