# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/BTagCSV_Data.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg --is-data --njobs=200
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/BTagCSV_Data.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_AntiBtag.cfg --is-data --njobs=200 #--no-tar --no-xrdcp-tar
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/BTagCSV_Data.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg --is-data --njobs=200 --no-tar --no-xrdcp-tar
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/BTagCSV_Data.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus_AntiBtag.cfg --is-data --njobs=200 --no-tar --no-xrdcp-tar
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_MY_60_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_300_MY_60_privateMC_PUweights.root --is-signal --xs=1 --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_MY_100_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_400_MY_100_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_MY_300_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_700_MY_300_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_MY_200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_900_MY_200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_MY_700_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1000_MY_700_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_700_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1600_MY_700_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_1200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1600_MY_1200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_2000_MY_1200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1800_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_2000_MY_1800_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1

python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_300_MY_60_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_300_MY_60_privateMC_PUweights.root --is-signal --xs=1 --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_400_MY_100_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_400_MY_100_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_700_MY_300_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_700_MY_300_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_900_MY_200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_900_MY_200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1000_MY_700_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1000_MY_700_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_700_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1600_MY_700_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_1600_MY_1200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_1600_MY_1200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1200_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_2000_MY_1200_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1
python scripts/submitSkimOnTier3.py --input=inputFiles/2016_NMSSM_XYH_bbbb_Datasets/NMSSM_XYH_bbbb_MX_2000_MY_1800_privateMC.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_Plus.cfg  --puWeight=weights/2016_NMSSM_XYH_bbbb_weights/NMSSM_XYH_bbbb_MX_2000_MY_1800_privateMC_PUweights.root --is-signal --xs=1  --no-tar --no-xrdcp-tar --njobs=1

#New triggers
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/SingleMuon_Data.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_triggerStudies.cfg --is-data --njobs=300
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MC_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_triggerStudies.cfg  --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --xs=1 --njobs=300

# Old triggers:
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MC_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B_triggerStudies.cfg  --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --xs=1 --njobs=300
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/SingleMuon_Data.txt  --tag=SingleMuon_nano104X_2016_triggerBits_v3  --cfg=config/skim_2016ResonantDiHiggs4B_triggerStudies.cfg --is-data --njobs=300


# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/BTagCSV_Data_FileList_80x_reprocess.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B_antiTag.cfg --is-data --njobs=300
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --is-signal --xs=1 --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/Resonant_NMSSM_bbbb/skim_2016Resonant_NMSSM_XYH_bbbb_2016Analysis.cfg --puWeight=weights/MCSignal_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=1
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3
# python scripts/submitSkimOnTier3.py --input=inputFiles/2016ResonantDiHiggs4BDataSets/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.txt  --tag=$1  --cfg=config/skim_2016ResonantDiHiggs4B.cfg --puWeight=weights/MCSignal_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=3




# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/Data_BTagCSV.txt  --tag=$1  --cfg=config/skim_DanielAnalysis.cfg --is-data --njobs=200
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/GluGluToHHTo4B_node_SM_13TeV-madgraph_correctedcfg_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT100to200_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT1500to2000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT2000toInf_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT200to300_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT500to700_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTToHadronic_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60
# python scripts/submitSkimOnTier3.py --input=inputFiles/DanielFiles/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local.txt  --tag=$1 --cfg=config/skim_DanielAnalysis.cfg --puWeight=weights/VBFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph_local_PUweights.root --is-signal --xs=1 --no-tar --no-xrdcp-tar --njobs=60




