python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_300_MY_125
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_400_MY_80
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_600_MY_125
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_700_MY_300
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_900_MY_500
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1000_MY_125
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1200_MY_800
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1400_MY_500
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1600_MY_300
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1600_MY_1000
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1800_MY_600
python prepareModels/runFullSelfBiasTest.py --config $1 --signal sig_NMSSM_bbbb_MX_1800_MY_1400