python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_kinFit
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_2_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree50_nLeaf_4_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_4_minEntries_700.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_4_minEntries_100.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree100_nLeaf_4_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_4_minEntries_500.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_10_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree200_nLeaf_4_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_4_minEntries_200.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree70_nLeaf_7_minEntries_300.
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2016_v2_PtRegressedAndHigherLevel_nTree400_nLeaf_4_minEntries_300.

python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2017_v2_PtRegressedAndHigherLevel
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2017_v2_PtRegressedAndHigherLevel_kinFit

python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2018_v3_PtRegressedAndHigherLevel
python mlskim_NMSSM_XYH_bbbb/ApplyBackgroundModel.py --dir BackgroundModels/Reweight_dataSubmission_2018_v3_PtRegressedAndHigherLevel_kinFit





